using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingSample.WebAPI.Models
{
    public class MeetingSampleWebAPIContext : DbContext
	{
		public MeetingSampleWebAPIContext(DbContextOptions<MeetingSampleWebAPIContext> options) : base(options)
		{
		}

        public DbSet<MeetingCategory> MeetingCategories { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Venue> Venues { get; set; }
        public DbSet<Meeting> Meetings { get; set; }
		public DbSet<Race> Races { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Lookup tables.
            modelBuilder.Entity<MeetingCategory>().HasData(
                new MeetingCategory { MeetingCategoryCode = 1, Description = "Professional", Meetings = null },
                new MeetingCategory { MeetingCategoryCode = 2, Description = "Picnic", Meetings = null },
                new MeetingCategory { MeetingCategoryCode = 3, Description = "Point to Point", Meetings = null },
                new MeetingCategory { MeetingCategoryCode = 4, Description = "Trail", Meetings = null }
            );

            modelBuilder.Entity<State>().HasData(
                new State { StateCode = 1, DescShort = "NSW", DescLong = "New South Wales" },
                new State { StateCode = 2, DescShort = "NT", DescLong = "Northern Territory" },
                new State { StateCode = 3, DescShort = "QLD", DescLong = "Queensland" },
                new State { StateCode = 4, DescShort = "SA", DescLong = "South Australia" },
                new State { StateCode = 5, DescShort = "TAS", DescLong = "Tasmania" },
                new State { StateCode = 6, DescShort = "VIC", DescLong = "Victoria" },
                new State { StateCode = 7, DescShort = "WA", DescLong = "Western Australia" }
            );

            modelBuilder.Entity<Venue>().HasData(
                new { VenueCode = 1, Name = "Adaminaby", StateCode = 1 },
                new { VenueCode = 2, Name = "Adelaide River", StateCode = 2 },
                new { VenueCode = 3, Name = "Albany", StateCode = 7 },
                new { VenueCode = 4, Name = "Albury", StateCode = 1 },
                new { VenueCode = 5, Name = "Alexandra", StateCode = 6 },
                new { VenueCode = 6, Name = "Ladbrokes Pioneer Park", StateCode = 2 },
                new { VenueCode = 7, Name = "Almaden", StateCode = 3 },
                new { VenueCode = 8, Name = "Alpha", StateCode = 3 },
                new { VenueCode = 9, Name = "Aramac", StateCode = 3 },
                new { VenueCode = 10, Name = "Ararat", StateCode = 6 },
                new { VenueCode = 11, Name = "Ardlethan", StateCode = 1 },
                new { VenueCode = 12, Name = "Armidale", StateCode = 1 },
                new { VenueCode = 13, Name = "Ascot", StateCode = 7 },
                new { VenueCode = 14, Name = "Ashburton", StateCode = 7 },
                new { VenueCode = 15, Name = "Atherton", StateCode = 3 },
                new { VenueCode = 16, Name = "Augathella", StateCode = 3 },
                new { VenueCode = 17, Name = "Avoca", StateCode = 6 },
                new { VenueCode = 18, Name = "Bairnsdale", StateCode = 6 },
                new { VenueCode = 19, Name = "Balaklava", StateCode = 4 },
                new { VenueCode = 20, Name = "Sportsbet-Ballarat", StateCode = 6 },
                new { VenueCode = 21, Name = "Ballina", StateCode = 1 },
                new { VenueCode = 22, Name = "Balnarring", StateCode = 6 },
                new { VenueCode = 23, Name = "Balranald", StateCode = 1 },
                new { VenueCode = 24, Name = "Baradine", StateCode = 1 },
                new { VenueCode = 25, Name = "Barcaldine", StateCode = 3 },
                new { VenueCode = 26, Name = "Barraba", StateCode = 1 },
                new { VenueCode = 27, Name = "Barrow Creek", StateCode = 2 },
                new { VenueCode = 28, Name = "Bathurst", StateCode = 1 },
                new { VenueCode = 29, Name = "Beaudesert", StateCode = 3 },
                new { VenueCode = 30, Name = "Bedgerebong", StateCode = 1 },
                new { VenueCode = 31, Name = "Bedourie", StateCode = 3 },
                new { VenueCode = 32, Name = "Bell", StateCode = 3 },
                new { VenueCode = 33, Name = "Belmont", StateCode = 7 },
                new { VenueCode = 34, Name = "Benalla", StateCode = 6 },
                new { VenueCode = 35, Name = "Bendigo", StateCode = 6 },
                new { VenueCode = 36, Name = "Berri", StateCode = 4 },
                new { VenueCode = 37, Name = "Berrigan", StateCode = 1 },
                new { VenueCode = 38, Name = "Betoota", StateCode = 3 },
                new { VenueCode = 39, Name = "Beverley", StateCode = 7 },
                new { VenueCode = 40, Name = "Bingara", StateCode = 1 },
                new { VenueCode = 41, Name = "Binnaway", StateCode = 1 },
                new { VenueCode = 42, Name = "Birdsville", StateCode = 3 },
                new { VenueCode = 43, Name = "Blackall", StateCode = 3 },
                new { VenueCode = 44, Name = "Bluff", StateCode = 3 },
                new { VenueCode = 45, Name = "Bombala", StateCode = 1 },
                new { VenueCode = 46, Name = "Bong Bong", StateCode = 1 },
                new { VenueCode = 47, Name = "Boorowa", StateCode = 1 },
                new { VenueCode = 48, Name = "Bordertown", StateCode = 4 },
                new { VenueCode = 49, Name = "Boulia", StateCode = 3 },
                new { VenueCode = 50, Name = "Bourke", StateCode = 1 },
                new { VenueCode = 51, Name = "Bowen", StateCode = 3 },
                new { VenueCode = 52, Name = "Bowraville", StateCode = 1 },
                new { VenueCode = 53, Name = "Braidwood", StateCode = 1 },
                new { VenueCode = 54, Name = "Brewarrina", StateCode = 1 },
                new { VenueCode = 55, Name = "Broken Hill", StateCode = 1 },
                new { VenueCode = 56, Name = "Broome", StateCode = 7 },
                new { VenueCode = 57, Name = "Buchan", StateCode = 6 },
                new { VenueCode = 58, Name = "Bunbury", StateCode = 7 },
                new { VenueCode = 59, Name = "Bundaberg", StateCode = 3 },
                new { VenueCode = 60, Name = "Bundarra", StateCode = 1 },
                new { VenueCode = 61, Name = "Burketown", StateCode = 3 },
                new { VenueCode = 62, Name = "Burrandowan", StateCode = 3 },
                new { VenueCode = 63, Name = "Burrumbeet", StateCode = 6 },
                new { VenueCode = 64, Name = "Cairns", StateCode = 3 },
                new { VenueCode = 65, Name = "Calliope", StateCode = 3 },
                new { VenueCode = 66, Name = "Camooweal", StateCode = 3 },
                new { VenueCode = 67, Name = "Camperdown", StateCode = 6 },
                new { VenueCode = 68, Name = "Canberra", StateCode = 1 },
                new { VenueCode = 69, Name = "Canterbury Park", StateCode = 1 },
                new { VenueCode = 70, Name = "Capella", StateCode = 3 },
                new { VenueCode = 71, Name = "Carinda", StateCode = 1 },
                new { VenueCode = 72, Name = "Carnarvon", StateCode = 7 },
                new { VenueCode = 73, Name = "Carrathool", StateCode = 1 },
                new { VenueCode = 74, Name = "Casino", StateCode = 1 },
                new { VenueCode = 75, Name = "Casterton", StateCode = 6 },
                new { VenueCode = 76, Name = "Caulfield", StateCode = 6 },
                new { VenueCode = 77, Name = "Ceduna", StateCode = 4 },
                new { VenueCode = 78, Name = "Cessnock", StateCode = 1 },
                new { VenueCode = 79, Name = "Charleville", StateCode = 3 },
                new { VenueCode = 80, Name = "Charters Towers", StateCode = 3 },
                new { VenueCode = 81, Name = "Cheltenham Park", StateCode = 4 },
                new { VenueCode = 82, Name = "Chillagoe", StateCode = 3 },
                new { VenueCode = 83, Name = "Chinchilla", StateCode = 3 },
                new { VenueCode = 84, Name = "Clare", StateCode = 4 },
                new { VenueCode = 85, Name = "Clermont", StateCode = 3 },
                new { VenueCode = 86, Name = "Clifton", StateCode = 3 },
                new { VenueCode = 87, Name = "Cloncurry", StateCode = 3 },
                new { VenueCode = 88, Name = "Cobar", StateCode = 1 },
                new { VenueCode = 89, Name = "Coen", StateCode = 3 },
                new { VenueCode = 90, Name = "Coffs Harbour", StateCode = 1 },
                new { VenueCode = 91, Name = "Colac", StateCode = 6 },
                new { VenueCode = 92, Name = "Coleraine", StateCode = 6 },
                new { VenueCode = 93, Name = "Collarenebri", StateCode = 1 },
                new { VenueCode = 94, Name = "Collie", StateCode = 7 },
                new { VenueCode = 95, Name = "Collinsville", StateCode = 3 },
                new { VenueCode = 96, Name = "Come-By-Chance", StateCode = 1 },
                new { VenueCode = 97, Name = "Condobolin", StateCode = 1 },
                new { VenueCode = 98, Name = "Cooktown", StateCode = 3 },
                new { VenueCode = 99, Name = "Coolabah", StateCode = 1 },
                new { VenueCode = 100, Name = "Cooma", StateCode = 1 },
                new { VenueCode = 101, Name = "Coonabarabran", StateCode = 1 },
                new { VenueCode = 102, Name = "Coonamble", StateCode = 1 },
                new { VenueCode = 103, Name = "Cootamundra", StateCode = 1 },
                new { VenueCode = 104, Name = "Corfield", StateCode = 3 },
                new { VenueCode = 105, Name = "Corowa", StateCode = 1 },
                new { VenueCode = 106, Name = "Cowra", StateCode = 1 },
                new { VenueCode = 107, Name = "Cranbourne", StateCode = 6 },
                new { VenueCode = 108, Name = "Crookwell", StateCode = 1 },
                new { VenueCode = 109, Name = "Cunnamulla", StateCode = 3 },
                new { VenueCode = 110, Name = "Dalby", StateCode = 3 },
                new { VenueCode = 111, Name = "Derby", StateCode = 7 },
                new { VenueCode = 112, Name = "Darwin", StateCode = 2 },
                new { VenueCode = 113, Name = "Dederang", StateCode = 6 },
                new { VenueCode = 114, Name = "Deepwater", StateCode = 1 },
                new { VenueCode = 115, Name = "Deloraine", StateCode = 5 },
                new { VenueCode = 116, Name = "Deniliquin", StateCode = 1 },
                new { VenueCode = 117, Name = "Devonport", StateCode = 5 },
                new { VenueCode = 118, Name = "Dingo", StateCode = 3 },
                new { VenueCode = 119, Name = "Donald", StateCode = 6 },
                new { VenueCode = 120, Name = "Dongara-Irwin", StateCode = 7 },
                new { VenueCode = 121, Name = "Doomben", StateCode = 3 },
                new { VenueCode = 122, Name = "Drouin", StateCode = 6 },
                new { VenueCode = 123, Name = "Duaringa", StateCode = 3 },
                new { VenueCode = 124, Name = "Dubbo", StateCode = 1 },
                new { VenueCode = 125, Name = "Dunkeld", StateCode = 6 },
                new { VenueCode = 126, Name = "Eagle Farm", StateCode = 3 },
                new { VenueCode = 127, Name = "Landor", StateCode = 7 },
                new { VenueCode = 128, Name = "Echuca", StateCode = 6 },
                new { VenueCode = 129, Name = "Edenhope", StateCode = 6 },
                new { VenueCode = 130, Name = "Eidsvold", StateCode = 3 },
                new { VenueCode = 131, Name = "Einasleigh", StateCode = 3 },
                new { VenueCode = 132, Name = "Hobart", StateCode = 5 },
                new { VenueCode = 133, Name = "Emerald", StateCode = 3 },
                new { VenueCode = 134, Name = "Enngonia", StateCode = 1 },
                new { VenueCode = 135, Name = "Eromanga", StateCode = 3 },
                new { VenueCode = 136, Name = "Esk", StateCode = 3 },
                new { VenueCode = 137, Name = "Esperance Bay", StateCode = 7 },
                new { VenueCode = 138, Name = "Ewan", StateCode = 3 },
                new { VenueCode = 139, Name = "Exmouth", StateCode = 7 },
                new { VenueCode = 140, Name = "Fitzroy", StateCode = 7 },
                new { VenueCode = 141, Name = "Flemington", StateCode = 6 },
                new { VenueCode = 142, Name = "Flinton", StateCode = 3 },
                new { VenueCode = 143, Name = "Forbes", StateCode = 1 },
                new { VenueCode = 144, Name = "Gatton", StateCode = 3 },
                new { VenueCode = 145, Name = "Gawler", StateCode = 4 },
                new { VenueCode = 146, Name = "Gayndah", StateCode = 3 },
                new { VenueCode = 147, Name = "bet365 Geelong", StateCode = 6 },
                new { VenueCode = 148, Name = "Georgetown", StateCode = 3 },
                new { VenueCode = 149, Name = "Geraldton", StateCode = 7 },
                new { VenueCode = 150, Name = "Geurie", StateCode = 1 },
                new { VenueCode = 151, Name = "Gilgandra", StateCode = 1 },
                new { VenueCode = 152, Name = "Gladstone", StateCode = 3 },
                new { VenueCode = 153, Name = "Glen Innes", StateCode = 1 },
                new { VenueCode = 154, Name = "Gold Coast", StateCode = 3 },
                new { VenueCode = 155, Name = "Goondiwindi", StateCode = 3 },
                new { VenueCode = 156, Name = "Gordonvale", StateCode = 3 },
                new { VenueCode = 157, Name = "Gosford", StateCode = 1 },
                new { VenueCode = 158, Name = "Goulburn", StateCode = 1 },
                new { VenueCode = 159, Name = "Grafton", StateCode = 1 },
                new { VenueCode = 160, Name = "Great Western", StateCode = 6 },
                new { VenueCode = 161, Name = "Gregory Downs", StateCode = 3 },
                new { VenueCode = 162, Name = "Grenfell", StateCode = 1 },
                new { VenueCode = 163, Name = "Griffith", StateCode = 1 },
                new { VenueCode = 164, Name = "Gulargambone", StateCode = 1 },
                new { VenueCode = 165, Name = "Gulgong", StateCode = 1 },
                new { VenueCode = 166, Name = "Gunbower", StateCode = 6 },
                new { VenueCode = 167, Name = "Gundagai", StateCode = 1 },
                new { VenueCode = 168, Name = "Gunnedah", StateCode = 1 },
                new { VenueCode = 169, Name = "Gympie", StateCode = 3 },
                new { VenueCode = 170, Name = "Hamilton", StateCode = 6 },
                new { VenueCode = 171, Name = "Hanging Rock", StateCode = 6 },
                new { VenueCode = 172, Name = "Harden", StateCode = 1 },
                new { VenueCode = 173, Name = "Hawker", StateCode = 4 },
                new { VenueCode = 174, Name = "Hawkesbury", StateCode = 1 },
                new { VenueCode = 175, Name = "Hay", StateCode = 1 },
                new { VenueCode = 176, Name = "Healesville", StateCode = 6 },
                new { VenueCode = 177, Name = "Hillston", StateCode = 1 },
                new { VenueCode = 178, Name = "Hinnomunjie", StateCode = 6 },
                new { VenueCode = 179, Name = "Holbrook", StateCode = 1 },
                new { VenueCode = 180, Name = "Home Hill", StateCode = 3 },
                new { VenueCode = 181, Name = "Horsham", StateCode = 6 },
                new { VenueCode = 182, Name = "Hughenden", StateCode = 3 },
                new { VenueCode = 183, Name = "Ilfracombe", StateCode = 3 },
                new { VenueCode = 184, Name = "Ingham", StateCode = 3 },
                new { VenueCode = 185, Name = "Injune", StateCode = 3 },
                new { VenueCode = 186, Name = "Innisfail", StateCode = 3 },
                new { VenueCode = 187, Name = "Inverell", StateCode = 1 },
                new { VenueCode = 188, Name = "Ipswich", StateCode = 3 },
                new { VenueCode = 189, Name = "Isisford", StateCode = 3 },
                new { VenueCode = 190, Name = "Jamestown", StateCode = 4 },
                new { VenueCode = 191, Name = "Jandowae", StateCode = 3 },
                new { VenueCode = 192, Name = "Jericho", StateCode = 3 },
                new { VenueCode = 193, Name = "Jerilderie", StateCode = 1 },
                new { VenueCode = 194, Name = "Julia Creek", StateCode = 3 },
                new { VenueCode = 195, Name = "Junction", StateCode = 7 },
                new { VenueCode = 196, Name = "Jundah", StateCode = 3 },
                new { VenueCode = 197, Name = "Kalgoorlie", StateCode = 7 },
                new { VenueCode = 198, Name = "Katherine", StateCode = 2 },
                new { VenueCode = 199, Name = "Kembla Grange", StateCode = 1 },
                new { VenueCode = 200, Name = "Kempsey", StateCode = 1 },
                new { VenueCode = 201, Name = "Kerang", StateCode = 6 },
                new { VenueCode = 202, Name = "Kilcoy", StateCode = 3 },
                new { VenueCode = 203, Name = "bet365 Park Kilmore", StateCode = 6 },
                new { VenueCode = 204, Name = "Kimba", StateCode = 4 },
                new { VenueCode = 205, Name = "Kimberley", StateCode = 7 },
                new { VenueCode = 206, Name = "King Island", StateCode = 5 },
                new { VenueCode = 207, Name = "Kingscote", StateCode = 4 },
                new { VenueCode = 208, Name = "Kojonup", StateCode = 7 },
                new { VenueCode = 209, Name = "Kumbia", StateCode = 3 },
                new { VenueCode = 210, Name = "Kununurra", StateCode = 7 },
                new { VenueCode = 211, Name = "bet365 Park Kyneton", StateCode = 6 },
                new { VenueCode = 212, Name = "Larrimah", StateCode = 2 },
                new { VenueCode = 213, Name = "Laura (SA)", StateCode = 4 },
                new { VenueCode = 214, Name = "Laverton", StateCode = 7 },
                new { VenueCode = 215, Name = "Leeton", StateCode = 1 },
                new { VenueCode = 216, Name = "Leinster", StateCode = 7 },
                new { VenueCode = 217, Name = "Leonora", StateCode = 7 },
                new { VenueCode = 218, Name = "Lightning Ridge", StateCode = 1 },
                new { VenueCode = 219, Name = "Lismore", StateCode = 1 },
                new { VenueCode = 220, Name = "Lock", StateCode = 4 },
                new { VenueCode = 221, Name = "Lockhart", StateCode = 1 },
                new { VenueCode = 222, Name = "Longford", StateCode = 5 },
                new { VenueCode = 223, Name = "Longreach", StateCode = 3 },
                new { VenueCode = 224, Name = "Louth", StateCode = 1 },
                new { VenueCode = 225, Name = "Mackay", StateCode = 3 },
                new { VenueCode = 226, Name = "Mallawa", StateCode = 1 },
                new { VenueCode = 227, Name = "Manangatang", StateCode = 6 },
                new { VenueCode = 228, Name = "Mansfield", StateCode = 6 },
                new { VenueCode = 229, Name = "Marble Bar", StateCode = 7 },
                new { VenueCode = 230, Name = "Mareeba", StateCode = 3 },
                new { VenueCode = 231, Name = "Mataranka", StateCode = 2 },
                new { VenueCode = 232, Name = "Maxwelton", StateCode = 3 },
                new { VenueCode = 233, Name = "McKinlay", StateCode = 3 },
                new { VenueCode = 234, Name = "Meekatharra", StateCode = 7 },
                new { VenueCode = 235, Name = "Mendooran", StateCode = 1 },
                new { VenueCode = 236, Name = "Merriwa", StateCode = 1 },
                new { VenueCode = 237, Name = "Merton", StateCode = 6 },
                new { VenueCode = 238, Name = "Middlemount", StateCode = 3 },
                new { VenueCode = 239, Name = "Mildura", StateCode = 6 },
                new { VenueCode = 240, Name = "Miles", StateCode = 3 },
                new { VenueCode = 241, Name = "Mindarie-Halidon", StateCode = 4 },
                new { VenueCode = 242, Name = "Mingela", StateCode = 3 },
                new { VenueCode = 243, Name = "Mingenew- Yandanooka", StateCode = 7 },
                new { VenueCode = 244, Name = "Mitchell", StateCode = 3 },
                new { VenueCode = 245, Name = "Moama", StateCode = 1 },
                new { VenueCode = 246, Name = "Moe", StateCode = 6 },
                new { VenueCode = 247, Name = "Monto", StateCode = 3 },
                new { VenueCode = 248, Name = "Moonee Valley", StateCode = 6 },
                new { VenueCode = 249, Name = "Moora", StateCode = 7 },
                new { VenueCode = 250, Name = "Moranbah", StateCode = 3 },
                new { VenueCode = 251, Name = "Moree", StateCode = 1 },
                new { VenueCode = 252, Name = "Mornington", StateCode = 6 },
                new { VenueCode = 253, Name = "Morphettville", StateCode = 4 },
                new { VenueCode = 254, Name = "Mortlake", StateCode = 6 },
                new { VenueCode = 255, Name = "Moruya", StateCode = 1 },
                new { VenueCode = 256, Name = "Morven", StateCode = 3 },
                new { VenueCode = 257, Name = "Moulamein", StateCode = 1 },
                new { VenueCode = 258, Name = "Mount Barker", StateCode = 7 },
                new { VenueCode = 259, Name = "Mount Gambier", StateCode = 4 },
                new { VenueCode = 260, Name = "Mount Garnet", StateCode = 3 },
                new { VenueCode = 261, Name = "Mount Isa", StateCode = 3 },
                new { VenueCode = 262, Name = "Mount Magnet", StateCode = 7 },
                new { VenueCode = 263, Name = "Mount Perry", StateCode = 3 },
                new { VenueCode = 264, Name = "Launceston", StateCode = 5 },
                new { VenueCode = 265, Name = "Mudgee", StateCode = 1 },
                new { VenueCode = 266, Name = "Mungery", StateCode = 1 },
                new { VenueCode = 267, Name = "Mungindi", StateCode = 1 },
                new { VenueCode = 268, Name = "Murray Bridge", StateCode = 4 },
                new { VenueCode = 269, Name = "Murtoa", StateCode = 6 },
                new { VenueCode = 270, Name = "Murwillumbah", StateCode = 1 },
                new { VenueCode = 271, Name = "Muswellbrook", StateCode = 1 },
                new { VenueCode = 272, Name = "Muttaburra", StateCode = 3 },
                new { VenueCode = 273, Name = "Nanango", StateCode = 3 },
                new { VenueCode = 274, Name = "Naracoorte", StateCode = 4 },
                new { VenueCode = 275, Name = "Narrabri", StateCode = 1 },
                new { VenueCode = 276, Name = "Narrandera", StateCode = 1 },
                new { VenueCode = 277, Name = "Narrogin", StateCode = 7 },
                new { VenueCode = 278, Name = "Narromine", StateCode = 1 },
                new { VenueCode = 279, Name = "Newcastle", StateCode = 1 },
                new { VenueCode = 280, Name = "Newman", StateCode = 7 },
                new { VenueCode = 281, Name = "Nhill", StateCode = 6 },
                new { VenueCode = 282, Name = "Noccundra", StateCode = 3 },
                new { VenueCode = 283, Name = "Noorama", StateCode = 3 },
                new { VenueCode = 284, Name = "Roebourne", StateCode = 7 },
                new { VenueCode = 285, Name = "Normanton", StateCode = 3 },
                new { VenueCode = 286, Name = "Norseman", StateCode = 7 },
                new { VenueCode = 287, Name = "Northam", StateCode = 7 },
                new { VenueCode = 288, Name = "Nowra", StateCode = 1 },
                new { VenueCode = 289, Name = "Nyngan", StateCode = 1 },
                new { VenueCode = 290, Name = "Oak Park", StateCode = 3 },
                new { VenueCode = 291, Name = "Oakbank", StateCode = 4 },
                new { VenueCode = 292, Name = "Oakey", StateCode = 3 },
                new { VenueCode = 293, Name = "Oakley", StateCode = 3 },
                new { VenueCode = 294, Name = "Orange", StateCode = 1 },
                new { VenueCode = 295, Name = "Pakenham", StateCode = 6 },
                new { VenueCode = 296, Name = "Parkes", StateCode = 1 },
                new { VenueCode = 297, Name = "Penola", StateCode = 4 },
                new { VenueCode = 298, Name = "Penong", StateCode = 4 },
                new { VenueCode = 299, Name = "Penshurst", StateCode = 6 },
                new { VenueCode = 300, Name = "Pentland", StateCode = 3 },
                new { VenueCode = 301, Name = "Pine Creek", StateCode = 2 },
                new { VenueCode = 302, Name = "Pingrup", StateCode = 7 },
                new { VenueCode = 303, Name = "Pinjarra Park", StateCode = 7 },
                new { VenueCode = 304, Name = "Pooncarie", StateCode = 1 },
                new { VenueCode = 305, Name = "Port Augusta", StateCode = 4 },
                new { VenueCode = 306, Name = "Port Hedland", StateCode = 7 },
                new { VenueCode = 307, Name = "Port Lincoln", StateCode = 4 },
                new { VenueCode = 308, Name = "Port Macquarie", StateCode = 1 },
                new { VenueCode = 309, Name = "Port Pirie", StateCode = 4 },
                new { VenueCode = 310, Name = "Prairie", StateCode = 3 },
                new { VenueCode = 311, Name = "Quambone", StateCode = 1 },
                new { VenueCode = 312, Name = "Quamby", StateCode = 3 },
                new { VenueCode = 313, Name = "Queanbeyan", StateCode = 1 },
                new { VenueCode = 314, Name = "Quilpie", StateCode = 3 },
                new { VenueCode = 315, Name = "Quirindi", StateCode = 1 },
                new { VenueCode = 316, Name = "Quorn", StateCode = 4 },
                new { VenueCode = 317, Name = "Royal Randwick", StateCode = 1 },
                new { VenueCode = 318, Name = "Renner", StateCode = 2 },
                new { VenueCode = 319, Name = "Richmond", StateCode = 3 },
                new { VenueCode = 320, Name = "Ridgelands", StateCode = 3 },
                new { VenueCode = 321, Name = "Rockhampton", StateCode = 3 },
                new { VenueCode = 322, Name = "Roma", StateCode = 3 },
                new { VenueCode = 323, Name = "Rosehill Gardens", StateCode = 1 },
                new { VenueCode = 324, Name = "Roxby Downs", StateCode = 4 },
                new { VenueCode = 325, Name = "Sale", StateCode = 6 },
                new { VenueCode = 326, Name = "Sandown", StateCode = 6 },
                new { VenueCode = 327, Name = "Scone", StateCode = 1 },
                new { VenueCode = 328, Name = "Sedan Dip", StateCode = 3 },
                new { VenueCode = 329, Name = "Seymour", StateCode = 6 },
                new { VenueCode = 330, Name = "Spreyton", StateCode = 5 },
                new { VenueCode = 331, Name = "Springsure", StateCode = 3 },
                new { VenueCode = 332, Name = "St Arnaud", StateCode = 6 },
                new { VenueCode = 333, Name = "St George", StateCode = 3 },
                new { VenueCode = 334, Name = "Stamford", StateCode = 3 },
                new { VenueCode = 335, Name = "Stanthorpe", StateCode = 3 },
                new { VenueCode = 336, Name = "Stawell", StateCode = 6 },
                new { VenueCode = 337, Name = "Stonehenge", StateCode = 3 },
                new { VenueCode = 338, Name = "Stony Creek", StateCode = 6 },
                new { VenueCode = 339, Name = "Strathalbyn", StateCode = 4 },
                new { VenueCode = 340, Name = "Streaky Bay", StateCode = 4 },
                new { VenueCode = 341, Name = "Surat", StateCode = 3 },
                new { VenueCode = 342, Name = "Swan Hill", StateCode = 6 },
                new { VenueCode = 343, Name = "Swifts Creek", StateCode = 6 },
                new { VenueCode = 344, Name = "Tabulam", StateCode = 1 },
                new { VenueCode = 345, Name = "Talmoi", StateCode = 1 },
                new { VenueCode = 346, Name = "Talwood", StateCode = 3 },
                new { VenueCode = 347, Name = "Tambo", StateCode = 3 },
                new { VenueCode = 348, Name = "Tamworth", StateCode = 1 },
                new { VenueCode = 349, Name = "Tara", StateCode = 3 },
                new { VenueCode = 350, Name = "Taree", StateCode = 1 },
                new { VenueCode = 351, Name = "Taroom", StateCode = 3 },
                new { VenueCode = 352, Name = "Tatura", StateCode = 6 },
                new { VenueCode = 353, Name = "Tennant Creek", StateCode = 2 },
                new { VenueCode = 354, Name = "Terang", StateCode = 6 },
                new { VenueCode = 355, Name = "Texas", StateCode = 3 },
                new { VenueCode = 356, Name = "Thangool", StateCode = 3 },
                new { VenueCode = 357, Name = "The Kennels", StateCode = 6 },
                new { VenueCode = 358, Name = "Theodore", StateCode = 3 },
                new { VenueCode = 359, Name = "Timber Creek", StateCode = 2 },
                new { VenueCode = 360, Name = "Tocumwal", StateCode = 1 },
                new { VenueCode = 361, Name = "Tomingley", StateCode = 1 },
                new { VenueCode = 362, Name = "Toodyay", StateCode = 7 },
                new { VenueCode = 363, Name = "Toowoomba", StateCode = 3 },
                new { VenueCode = 364, Name = "Tottenham", StateCode = 1 },
                new { VenueCode = 365, Name = "Tower Hill", StateCode = 3 },
                new { VenueCode = 366, Name = "Townsville", StateCode = 3 },
                new { VenueCode = 367, Name = "Towong", StateCode = 6 },
                new { VenueCode = 368, Name = "Trangie", StateCode = 1 },
                new { VenueCode = 369, Name = "Traralgon", StateCode = 6 },
                new { VenueCode = 370, Name = "Trundle", StateCode = 1 },
                new { VenueCode = 371, Name = "Tullamore", StateCode = 1 },
                new { VenueCode = 372, Name = "Tumbarumba", StateCode = 1 },
                new { VenueCode = 373, Name = "Tumby Bay", StateCode = 4 },
                new { VenueCode = 374, Name = "Tumut", StateCode = 1 },
                new { VenueCode = 375, Name = "Twin Hills", StateCode = 3 },
                new { VenueCode = 376, Name = "Victoria Park", StateCode = 4 },
                new { VenueCode = 377, Name = "Wagga", StateCode = 1 },
                new { VenueCode = 378, Name = "Walcha", StateCode = 1 },
                new { VenueCode = 379, Name = "Walgett", StateCode = 1 },
                new { VenueCode = 380, Name = "Wallabadah", StateCode = 1 },
                new { VenueCode = 381, Name = "Wamboyne", StateCode = 1 },
                new { VenueCode = 382, Name = "Wandoan", StateCode = 3 },
                new { VenueCode = 383, Name = "Wangaratta", StateCode = 6 },
                new { VenueCode = 384, Name = "Warialda", StateCode = 1 },
                new { VenueCode = 385, Name = "Warra", StateCode = 3 },
                new { VenueCode = 386, Name = "Warracknabeal", StateCode = 6 },
                new { VenueCode = 387, Name = "Warren", StateCode = 1 },
                new { VenueCode = 388, Name = "Warrnambool", StateCode = 6 },
                new { VenueCode = 389, Name = "Warwick", StateCode = 3 },
                new { VenueCode = 390, Name = "Warwick Farm", StateCode = 1 },
                new { VenueCode = 391, Name = "Wauchope", StateCode = 1 },
                new { VenueCode = 392, Name = "Wean", StateCode = 1 },
                new { VenueCode = 393, Name = "Wellington", StateCode = 1 },
                new { VenueCode = 394, Name = "Wentworth", StateCode = 1 },
                new { VenueCode = 395, Name = "Werribee", StateCode = 6 },
                new { VenueCode = 396, Name = "Werribee Park", StateCode = 6 },
                new { VenueCode = 397, Name = "Wilpeena", StateCode = 3 },
                new { VenueCode = 398, Name = "Wiluna", StateCode = 7 },
                new { VenueCode = 399, Name = "Windorah", StateCode = 3 },
                new { VenueCode = 400, Name = "Winton", StateCode = 3 },
                new { VenueCode = 401, Name = "Wodonga", StateCode = 6 },
                new { VenueCode = 402, Name = "Wondai", StateCode = 3 },
                new { VenueCode = 403, Name = "Woolamai", StateCode = 6 },
                new { VenueCode = 404, Name = "Wyandra", StateCode = 3 },
                new { VenueCode = 405, Name = "Wyndham", StateCode = 7 },
                new { VenueCode = 406, Name = "Wyong", StateCode = 1 },
                new { VenueCode = 407, Name = "Yalgoo", StateCode = 7 },
                new { VenueCode = 408, Name = "Yaraka", StateCode = 3 },
                new { VenueCode = 409, Name = "Yarra Valley", StateCode = 6 },
                new { VenueCode = 410, Name = "Yass", StateCode = 1 },
                new { VenueCode = 411, Name = "Yea", StateCode = 6 },
                new { VenueCode = 412, Name = "Yeppoon", StateCode = 3 },
                new { VenueCode = 413, Name = "York", StateCode = 7 },
                new { VenueCode = 414, Name = "Young", StateCode = 1 },
                new { VenueCode = 415, Name = "Arrilalah", StateCode = 3 },
                new { VenueCode = 416, Name = "Camboon", StateCode = 3 },
                new { VenueCode = 417, Name = "Sunshine Coast", StateCode = 3 },
                new { VenueCode = 418, Name = "Hebel", StateCode = 3 },
                new { VenueCode = 419, Name = "Laura (Q)", StateCode = 3 },
                new { VenueCode = 421, Name = "Bowen River", StateCode = 3 },
                new { VenueCode = 422, Name = "Sapphire Coast", StateCode = 1 },
                new { VenueCode = 423, Name = "Yarra Glen Hunt", StateCode = 6 },
                new { VenueCode = 424, Name = "Deagon", StateCode = 3 },
                new { VenueCode = 425, Name = "Cranbourne-Trn", StateCode = 6 },
                new { VenueCode = 426, Name = "Kensington", StateCode = 1 },
                new { VenueCode = 427, Name = "Lark Hill", StateCode = 7 },
                new { VenueCode = 428, Name = "Ladbrokes Park Hillside", StateCode = 6 },
                new { VenueCode = 429, Name = "Ladbrokes Park Lakeside", StateCode = 6 },
                new { VenueCode = 430, Name = "Wycheproof", StateCode = 6 },
                new { VenueCode = 431, Name = "Tuncurry", StateCode = 1 },
                new { VenueCode = 432, Name = "Canberra Acton", StateCode = 1 },
                new { VenueCode = 433, Name = "bet365 Geelong Synthetic", StateCode = 6 },
                new { VenueCode = 434, Name = "Sunshine Coast Cushion Track", StateCode = 3 },
                new { VenueCode = 435, Name = "Morphettville Parks", StateCode = 4 },
                new { VenueCode = 436, Name = "Toowoomba Cushion Track", StateCode = 3 },
                new { VenueCode = 437, Name = "Hobart Inside Track", StateCode = 5 },
                new { VenueCode = 438, Name = "Rockhampton Sand Track", StateCode = 3 },
                new { VenueCode = 439, Name = "Sunshine Coast@Inner Track", StateCode = 3 },
                new { VenueCode = 440, Name = "Tullibigeal", StateCode = 1 },
                new { VenueCode = 441, Name = "Cranbourne-Syn", StateCode = 6 },
                new { VenueCode = 442, Name = "Devonport Tapeta Synthetic", StateCode = 5 },
                new { VenueCode = 443, Name = "Millicent", StateCode = 4 },
                new { VenueCode = 444, Name = "Hawkesbury Inner", StateCode = 1 },
                new { VenueCode = 445, Name = "Toowoomba Inner Track", StateCode = 3 },
                new { VenueCode = 446, Name = "Fernhill", StateCode = 1 },
                new { VenueCode = 447, Name = "Wagga Riverside", StateCode = 1 },
                new { VenueCode = 448, Name = "Racing.com Park Synthetic", StateCode = 6 },
                new { VenueCode = 449, Name = "Nine Dragons", StateCode = 6 },
                new { VenueCode = 450, Name = "Beaumont Newcastle", StateCode = 1 },
                new { VenueCode = 451, Name = "Cairns Night", StateCode = 3 },
                new { VenueCode = 452, Name = "Racing.com Park", StateCode = 6 }
            );

            modelBuilder.Entity<Meeting>().HasData(
                new { MeetCode = 1, MeetDate = new DateTime(2018, 1, 1), Title = "Meeting 1", MeetingCategoryCode = 1, StateCode = 6, VenueCode = 141 },
                new { MeetCode = 2, MeetDate = new DateTime(2018, 1, 1), Title = "Meeting 2", MeetingCategoryCode = 1, StateCode = 6, VenueCode = 76 },
                new { MeetCode = 3, MeetDate = new DateTime(2018, 1, 3), Title = "Meeting 3", MeetingCategoryCode = 1, StateCode = 6, VenueCode = 141 },
                new { MeetCode = 4, MeetDate = new DateTime(2018, 1, 4), Title = "Meeting 4", MeetingCategoryCode = 1, StateCode = 6, VenueCode = 76 },
                new { MeetCode = 5, MeetDate = new DateTime(2018, 1, 5), Title = "Meeting 5", MeetingCategoryCode = 1, StateCode = 6, VenueCode = 141 }
            );

            modelBuilder.Entity<Race>().HasData(
                new { RaceCode = 1, MeetCode = 1, RaceNumber = 1, Name = "Meeting 1, Race 1", Distance = 1000 },
                new { RaceCode = 2, MeetCode = 1, RaceNumber = 2, Name = "Meeting 1, Race 2", Distance = 1200 },
                new { RaceCode = 3, MeetCode = 1, RaceNumber = 3, Name = "Meeting 1, Race 3", Distance = 1300 },
                new { RaceCode = 4, MeetCode = 2, RaceNumber = 1, Name = "Meeting 2, Race 1", Distance = 1000 },
                new { RaceCode = 5, MeetCode = 2, RaceNumber = 2, Name = "Meeting 2, Race 2", Distance = 1200 },
                new { RaceCode = 6, MeetCode = 2, RaceNumber = 3, Name = "Meeting 2, Race 3", Distance = 1300 },
                new { RaceCode = 7, MeetCode = 2, RaceNumber = 4, Name = "Meeting 2, Race 4", Distance = 1000 }
            );
        }
    }
}
